name: Translate README

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Permette di eseguirlo manualmente

permissions:
  contents: write

jobs:
  translate_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Versione più aggiornata

      # Italian
      - name: Translate to Italian
        uses: dephraiim/translate-readme@main
        with:
          LANG: it
        env:
          OUTPUT_PATH: ./README.it.md
        continue-on-error: true

      # French  
      - name: Translate to French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
        env:
          OUTPUT_PATH: ./README.fr.md
        continue-on-error: true

      # Spanish
      - name: Translate to Spanish
        uses: dephraiim/translate-readme@main
        with:
          LANG: es
        env:
          OUTPUT_PATH: ./README.es.md
        continue-on-error: true

      # German
      - name: Translate to German
        uses: dephraiim/translate-readme@main
        with:
          LANG: de
        env:
          OUTPUT_PATH: ./README.de.md
        continue-on-error: true

      # Japanese
      - name: Translate to Japanese
        uses: dephraiim/translate-readme@main
        with:
          LANG: ja
        env:
          OUTPUT_PATH: ./README.ja.md
        continue-on-error: true

      # Chinese (Simplified)
      - name: Translate to Chinese (Simplified)
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
        env:
          OUTPUT_PATH: ./README.zh-CN.md
        continue-on-error: true

      # Russian
      - name: Translate to Russian
        uses: dephraiim/translate-readme@main
        with:
          LANG: ru
        env:
          OUTPUT_PATH: ./README.ru.md
        continue-on-error: true

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.*.md
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Auto-translate READMEs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi