name: Translate README

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  translate_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Translate READMEs
        run: |
          langs=(it fr es de ja zh-CN ru)
          for lang in "${langs[@]}"; do
            echo "Translating to $lang..."
            npx translate-readme --lang "$lang" --output "./README.$lang.md" || echo "❌ Failed to translate $lang"
          done

      - name: Commit and push translated files
        run: |
          set -e
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add README.*.md || echo "No README translations to add"

          if ! git diff --cached --quiet; then
            git commit -m "Auto-translate READMEs"
            git push
          else
            echo "No changes to commit."
          fi
